const CREATE_LINK = 'CREATE_LINK'
const LINK_CREATED_SUCCESSFULLY = 'LINK_CREATED_SUCCESSFULLY'

const SIGN_IN = 'SIGN_IN'
const SIGN_OUT = 'SIGN_OUT'

export default {
  CREATE_LINK,
  LINK_CREATED_SUCCESSFULLY,
  SIGN_IN,
  SIGN_OUT
}