const CREATE_LINK = 'CREATE_LINK'
const LINK_CREATED_SUCCESSFULLY = 'LINK_CREATED_SUCCESSFULLY'

const SIGN_IN = 'SIGN_IN'
const SIGN_OUT = 'SIGN_OUT'

const ADD_LINK_TO_DELETE = 'ADD_LINK_TO_DELETE'
const REMOVE_LINK_TO_DELETE = 'REMOVE_LINK_TO_DELETE'
const TURN_ON_DELETE_MOD = 'TURN_ON_DELETE_MOD'
const TURN_OFF_DELETE_MOD = 'TURN_OFF_DELETE_MOD'
const DELETE_LINKS = 'DELETE_LINKS'

export default {
  CREATE_LINK,
  LINK_CREATED_SUCCESSFULLY,
  SIGN_IN,
  SIGN_OUT,
  ADD_LINK_TO_DELETE,
  REMOVE_LINK_TO_DELETE,
  TURN_ON_DELETE_MOD,
  TURN_OFF_DELETE_MOD,
  DELETE_LINKS
}